questions = [
    {
        "question": "What is Python?",
        "A": "An operating system",
        "B": "An interpreted programming language",
        "C": "A database",
        "D": "A web browser",
        "answer": "An interpreted programming language"
    },
    
    {
        "question": "Who developed Python?",
        "A": "James Gosling",
        "B": "Dennis Ritchie",
        "C": "Guido van Rossum",
        "D": "Bjarne Stroustrup",
        "answer": "Guido van Rossum"
    },
    
    {
        "question": "Why is Python called an interpreted language?",
        "A": "It is executed by an interpreter",
        "B": "It is converted directly to machine code",
        "C": "It does not require a CPU",
        "D": "It is only used for web development",
        "answer": "It is executed by an interpreter"
    },
    
    {
        "question": "What is a key feature of Python?",
        "A": "Platform dependent",
        "B": "Low-level programming",
        "C": "Dynamic typing",
        "D": "Manual memory management",
        "answer": "Dynamic typing"
    },
    
    {
        "question": "Why is Python platform independent?",
        "A": "It runs without an operating system",
        "B": "Python code can run on multiple operating systems with a compatible interpreter",
        "C": "It only works on Windows",
        "D": "It only works on Linux",
        "answer": "Python code can run on multiple operating systems with a compatible interpreter"
    },
    
    {
        "question": "What is bytecode in Python?",
        "A": "Machine code",
        "B": "Assembly code",
        "C": "Intermediate code generated by Python",
        "D": "Source code",
        "answer": "Intermediate code generated by Python"
    },
    
    {
        "question": "What does PVM stand for?",
        "A": "Python Variable Manager",
        "B": "Python Virtual Machine",
        "C": "Program Virtual Memory",
        "D": "Python Version Manager",
        "answer": "Python Virtual Machine"
    },
    
    {
        "question": "What is the purpose of the Python Virtual Machine (PVM)?",
        "A": "To edit Python code",
        "B": "To execute Python bytecode",
        "C": "To compile C programs",
        "D": "To create databases",
        "answer": "To execute Python bytecode"
    },
    
    {
        "question": "What is a .pyc file?",
        "A": "A Python source file",
        "B": "A compiled bytecode file",
        "C": "A text file",
        "D": "A configuration file",
        "answer": "A compiled bytecode file"
    },
    
    {
        "question": "What is the purpose of the __pycache__ folder?",
        "A": "To store images",
        "B": "To store Python bytecode files",
        "C": "To store Python source code",
        "D": "To store user data",
        "answer": "To store Python bytecode files"
    },
    
    {
        "question": "What is source code?",
        "A": "Code written by the programmer",
        "B": "Machine language",
        "C": "Assembly language",
        "D": "Binary code",
        "answer": "Code written by the programmer"
    },
    
    {
        "question": "What is machine code?",
        "A": "Python code",
        "B": "Code written in English",
        "C": "Binary instructions executed by the CPU",
        "D": "Bytecode",
        "answer": "Binary instructions executed by the CPU"
    },
    
    {
        "question": "What is parsing in Python?",
        "A": "Executing bytecode",
        "B": "Checking source code for correct syntax",
        "C": "Deleting errors",
        "D": "Compiling machine code",
        "answer": "Checking source code for correct syntax"
    },
    
    {
        "question": "What is an Abstract Syntax Tree (AST)?",
        "A": "A tree representing the structure of source code",
        "B": "A folder used by Python",
        "C": "A machine code file",
        "D": "A type of loop",
        "answer": "A tree representing the structure of source code"
    },
    
    {
        "question": "What is the main purpose of the AST?",
        "A": "To store variables",
        "B": "To help Python generate bytecode",
        "C": "To display output",
        "D": "To execute machine code",
        "answer": "To help Python generate bytecode"
    },
    
    {
        "question": "Which step comes immediately after parsing?",
        "A": "Machine code generation",
        "B": "AST generation",
        "C": "Program execution",
        "D": "Printing output",
        "answer": "AST generation"
    },
    
    {
        "question": "Does Python compile code before execution?",
        "A": "No, never",
        "B": "Yes, it compiles source code into bytecode",
        "C": "Only on Linux",
        "D": "Only when using IDLE",
        "answer": "Yes, it compiles source code into bytecode"
    },
    
    {
        "question": "What is dynamic typing in Python?",
        "A": "Variables can change their data type at runtime",
        "B": "Variables must be declared before use",
        "C": "Variables cannot change type",
        "D": "Variables are always integers",
        "answer": "Variables can change their data type at runtime"
    },
    
    {
        "question": "What is the advantage of Python being a high-level language?",
        "A": "It requires writing machine code",
        "B": "It is easier to read and write",
        "C": "It only works on one platform",
        "D": "It cannot use libraries",
        "answer": "It is easier to read and write"
    },
    
    {
        "question": "Which statement best describes Python execution?",
        "A": "Source Code → Machine Code → CPU",
        "B": "Source Code → Bytecode → PVM",
        "C": "Source Code → Database → CPU",
        "D": "Source Code → HTML → Browser",
        "answer": "Source Code → Bytecode → PVM"
    },
    
    {
        "question": "What is a variable in Python?",
        "A": "A reserved keyword",
        "B": "A named reference to an object",
        "C": "A built-in function",
        "D": "A data type",
        "answer": "A named reference to an object"
    },
    
    {
        "question": "Why is there no need to declare variable types in Python?",
        "A": "Python is dynamically typed",
        "B": "Variables are always integers",
        "C": "Python is a compiled language",
        "D": "Variables cannot change",
        "answer": "Python is dynamically typed"
    },
    
    {
        "question": "Can a variable change its data type in Python?",
        "A": "No",
        "B": "Only once",
        "C": "Yes",
        "D": "Only for numbers",
        "answer": "Yes"
    },
    
    {
        "question": "What are the built-in data types in Python?",
        "A": "int, float, str, list, tuple, set, dict, bool, NoneType",
        "B": "int, char, float",
        "C": "array, vector, map",
        "D": "Only int and str",
        "answer": "int, float, str, list, tuple, set, dict, bool, NoneType"
    },
    
    {
        "question": "What does None represent in Python?",
        "A": "Zero",
        "B": "An empty string",
        "C": "The absence of a value",
        "D": "False",
        "answer": "The absence of a value"
    },
    
    {
        "question": "Which function returns the data type of an object?",
        "A": "id()",
        "B": "type()",
        "C": "len()",
        "D": "input()",
        "answer": "type()"
    },
    
    {
        "question": "What is the purpose of isinstance()?",
        "A": "To create objects",
        "B": "To check whether an object belongs to a specified type",
        "C": "To convert data types",
        "D": "To compare values",
        "answer": "To check whether an object belongs to a specified type"
    },
    
    {
        "question": "Which of the following is mutable?",
        "A": "Tuple",
        "B": "String",
        "C": "List",
        "D": "Integer",
        "answer": "List"
    },
    
    {
        "question": "Which of the following is immutable?",
        "A": "Dictionary",
        "B": "Set",
        "C": "List",
        "D": "Tuple",
        "answer": "Tuple"
    },
    
    {
        "question": "Why are strings immutable in Python?",
        "A": "To improve performance and reliability",
        "B": "To save disk space",
        "C": "To reduce file size",
        "D": "Because they are numbers",
        "answer": "To improve performance and reliability"
    },
    
    {
        "question": "What is an identifier?",
        "A": "A built-in function",
        "B": "A name used to identify variables, functions, classes, or objects",
        "C": "A Python keyword",
        "D": "A comment",
        "answer": "A name used to identify variables, functions, classes, or objects"
    },
    
    {
        "question": "Which character can an identifier start with?",
        "A": "A digit",
        "B": "A space",
        "C": "A letter or underscore (_)",
        "D": "A special character",
        "answer": "A letter or underscore (_)"
    },
    
    {
        "question": "Can an identifier start with a number?",
        "A": "Yes",
        "B": "Only in Python 3",
        "C": "No",
        "D": "Only if it contains letters",
        "answer": "No"
    },
    
    {
        "question": "What is the difference between an identifier and a keyword?",
        "A": "Keywords can be used as variable names",
        "B": "Identifiers are user-defined names, while keywords have predefined meanings",
        "C": "There is no difference",
        "D": "Identifiers are only used for functions",
        "answer": "Identifiers are user-defined names, while keywords have predefined meanings"
    },
    
    {
        "question": "Is Python case-sensitive?",
        "A": "No",
        "B": "Yes",
        "C": "Only for keywords",
        "D": "Only for strings",
        "answer": "Yes"
    },
    
    {
        "question": "What is multiple assignment?",
        "A": "Assigning multiple values to multiple variables in one statement",
        "B": "Assigning one value many times",
        "C": "Using multiple print() statements",
        "D": "Creating multiple functions",
        "answer": "Assigning multiple values to multiple variables in one statement"
    },
    
    {
        "question": "What is chain assignment?",
        "A": "Assigning different values to one variable",
        "B": "Assigning the same value to multiple variables",
        "C": "Assigning multiple functions",
        "D": "Assigning lists to tuples",
        "answer": "Assigning the same value to multiple variables"
    },
    
    {
        "question": "How can two variables be swapped without using a third variable?",
        "A": "Using tuple unpacking",
        "B": "Using a loop",
        "C": "Using recursion",
        "D": "It is not possible",
        "answer": "Using tuple unpacking"
    },
    
    {
        "question": "What does the id() function return?",
        "A": "The data type of an object",
        "B": "The memory identity of an object",
        "C": "The size of an object",
        "D": "The value of an object",
        "answer": "The memory identity of an object"
    },
    
    {
        "question": "What does object identity represent in Python?",
        "A": "The object's data type",
        "B": "The object's unique memory identity during its lifetime",
        "C": "The object's size",
        "D": "The object's value",
        "answer": "The object's unique memory identity during its lifetime"
    },
    
    {
        "question": "What is input() in Python?",
        "A": "A function used to display output",
        "B": "A function used to take user input",
        "C": "A function used to open files",
        "D": "A function used to import modules",
        "answer": "A function used to take user input"
    },
    
    {
        "question": "Why does input() always return a string?",
        "A": "Because Python automatically stores all user input as text",
        "B": "Because strings use less memory",
        "C": "Because integers are not supported",
        "D": "Because input() returns a list",
        "answer": "Because Python automatically stores all user input as text"
    },
    
    {
        "question": "What is print() in Python?",
        "A": "A function used to display output",
        "B": "A function used to take input",
        "C": "A function used to create variables",
        "D": "A function used to delete variables",
        "answer": "A function used to display output"
    },
    
    {
        "question": "How can you take integer input from the user?",
        "A": "float(input())",
        "B": "str(input())",
        "C": "int(input())",
        "D": "bool(input())",
        "answer": "int(input())"
    },
    
    {
        "question": "How can you take float input from the user?",
        "A": "int(input())",
        "B": "float(input())",
        "C": "str(input())",
        "D": "list(input())",
        "answer": "float(input())"
    },
    
    {
        "question": "How can you take multiple inputs in one line?",
        "A": "Using split()",
        "B": "Using append()",
        "C": "Using pop()",
        "D": "Using remove()",
        "answer": "Using split()"
    },
    
    {
        "question": "What is the purpose of the sep parameter in print()?",
        "A": "To end the output",
        "B": "To separate multiple values",
        "C": "To format numbers",
        "D": "To take input",
        "answer": "To separate multiple values"
    },
    
    {
        "question": "What is the purpose of the end parameter in print()?",
        "A": "To specify what is printed at the end of the output",
        "B": "To separate values",
        "C": "To convert data types",
        "D": "To stop the program",
        "answer": "To specify what is printed at the end of the output"
    },
    
    {
        "question": "What is type casting?",
        "A": "Converting one data type into another",
        "B": "Creating a variable",
        "C": "Deleting an object",
        "D": "Printing output",
        "answer": "Converting one data type into another"
    },
    
    {
        "question": "What is implicit type conversion?",
        "A": "Conversion performed automatically by Python",
        "B": "Conversion done using int()",
        "C": "Conversion done using float()",
        "D": "Conversion done by the user",
        "answer": "Conversion performed automatically by Python"
    },
    
    {
        "question": "What is explicit type conversion?",
        "A": "Conversion performed automatically",
        "B": "Conversion performed using type conversion functions",
        "C": "Conversion performed by the operating system",
        "D": "Conversion performed by the compiler",
        "answer": "Conversion performed using type conversion functions"
    },
    
    {
        "question": "Which function converts a value to an integer?",
        "A": "str()",
        "B": "bool()",
        "C": "int()",
        "D": "list()",
        "answer": "int()"
    },
    
    {
        "question": "Which function converts a value to a floating-point number?",
        "A": "float()",
        "B": "int()",
        "C": "tuple()",
        "D": "dict()",
        "answer": "float()"
    },
    
    {
        "question": "Which function converts a value to a string?",
        "A": "bool()",
        "B": "str()",
        "C": "set()",
        "D": "list()",
        "answer": "str()"
    },
    
    {
        "question": "Which function converts a value to a Boolean?",
        "A": "int()",
        "B": "float()",
        "C": "bool()",
        "D": "dict()",
        "answer": "bool()"
    },
    
    {
        "question": "Can every string be converted to an integer using int()?",
        "A": "Yes",
        "B": "No",
        "C": "Only empty strings",
        "D": "Only strings containing letters",
        "answer": "No"
    },
    
    {
        "question": "What happens when a float is converted to an integer using int()?",
        "A": "It is rounded to the nearest integer",
        "B": "The decimal part is removed",
        "C": "It becomes a string",
        "D": "It becomes a Boolean",
        "answer": "The decimal part is removed"
    },
    
    {
        "question": "Which error occurs if type conversion fails?",
        "A": "TypeError",
        "B": "ValueError",
        "C": "NameError",
        "D": "IndexError",
        "answer": "ValueError"
    },
    
    {
        "question": "What is the purpose of f-strings?",
        "A": "To create functions",
        "B": "To format strings easily",
        "C": "To convert data types",
        "D": "To create files",
        "answer": "To format strings easily"
    },
    
    {
        "question": "Which method can also be used for string formatting?",
        "A": "replace()",
        "B": "format()",
        "C": "append()",
        "D": "copy()",
        "answer": "format()"
    },
    
    {
        "question": "Which operator performs floating-point division in Python?",
        "A": "/",
        "B": "//",
        "C": "%",
        "D": "**",
        "answer": "/"
    },
    
    {
        "question": "Which operator performs floor division in Python?",
        "A": "/",
        "B": "//",
        "C": "%",
        "D": "**",
        "answer": "//"
    },
    
    {
        "question": "What is the purpose of the % operator?",
        "A": "Performs exponentiation",
        "B": "Returns the remainder after division",
        "C": "Performs floor division",
        "D": "Performs multiplication",
        "answer": "Returns the remainder after division"
    },
    
    {
        "question": "Which operator is used for exponentiation in Python?",
        "A": "^",
        "B": "**",
        "C": "//",
        "D": "%",
        "answer": "**"
    },
    
    {
        "question": "Why is ^ not used as the power operator in Python?",
        "A": "It is reserved for comments",
        "B": "It is the bitwise XOR operator",
        "C": "It is the division operator",
        "D": "It is used for multiplication",
        "answer": "It is the bitwise XOR operator"
    },
    
    {
        "question": "Which of the following is an assignment operator?",
        "A": "==",
        "B": "+=",
        "C": ">=",
        "D": "!=",
        "answer": "+="
    },
    
    {
        "question": "What is the difference between = and == ?",
        "A": "= compares values, == assigns values",
        "B": "= assigns values, == compares values",
        "C": "Both perform the same operation",
        "D": "= is used only for numbers",
        "answer": "= assigns values, == compares values"
    },
    
    {
        "question": "What does += do internally?",
        "A": "Adds two variables and stores the result in the same variable",
        "B": "Subtracts two variables",
        "C": "Compares two variables",
        "D": "Deletes the variable",
        "answer": "Adds two variables and stores the result in the same variable"
    },
    
    {
        "question": "Which of the following is a relational operator?",
        "A": ">",
        "B": "&",
        "C": "+",
        "D": "%",
        "answer": ">"
    },
    
    {
        "question": "Can relational operators be chained in Python?",
        "A": "Yes",
        "B": "No",
        "C": "Only with integers",
        "D": "Only with strings",
        "answer": "Yes"
    },
    
    {
        "question": "What are logical operators in Python?",
        "A": "and, or, not",
        "B": "+, -, *",
        "C": ">, <, ==",
        "D": "&, |, ^",
        "answer": "and, or, not"
    },
    
    {
        "question": "What does the and operator return?",
        "A": "True if both operands are True",
        "B": "True if at least one operand is True",
        "C": "Always True",
        "D": "Always False",
        "answer": "True if both operands are True"
    },
    
    {
        "question": "What does the or operator return?",
        "A": "True only if both operands are True",
        "B": "True if at least one operand is True",
        "C": "Always False",
        "D": "Always True",
        "answer": "True if at least one operand is True"
    },
    
    {
        "question": "What does the not operator do?",
        "A": "Adds two values",
        "B": "Reverses the Boolean value",
        "C": "Compares two values",
        "D": "Performs multiplication",
        "answer": "Reverses the Boolean value"
    },
    
    {
        "question": "Which operator checks whether a value exists in a sequence?",
        "A": "is",
        "B": "in",
        "C": "==",
        "D": "&",
        "answer": "in"
    },
    
    {
        "question": "Which operator checks whether a value does not exist in a sequence?",
        "A": "not",
        "B": "!=",
        "C": "not in",
        "D": "is not",
        "answer": "not in"
    },
    
    {
        "question": "Which are the identity operators in Python?",
        "A": "is and is not",
        "B": "== and !=",
        "C": "in and not in",
        "D": "& and |",
        "answer": "is and is not"
    },
    
    {
        "question": "What is the difference between is and == ?",
        "A": "Both compare object identity",
        "B": "is compares object identity, == compares values",
        "C": "== compares object identity, is compares values",
        "D": "There is no difference",
        "answer": "is compares object identity, == compares values"
    },
    
    {
        "question": "What are bitwise operators used for?",
        "A": "Working with individual bits of integers",
        "B": "Comparing strings",
        "C": "Creating variables",
        "D": "Reading files",
        "answer": "Working with individual bits of integers"
    },
    
    {
        "question": "What is the purpose of the XOR (^) operator?",
        "A": "Performs exponentiation",
        "B": "Returns 1 when corresponding bits are different",
        "C": "Returns the remainder",
        "D": "Performs floor division",
        "answer": "Returns 1 when corresponding bits are different"
    },
    
    {
        "question": "What is an if statement?",
        "A": "A loop",
        "B": "A conditional statement used to make decisions",
        "C": "A function",
        "D": "A module",
        "answer": "A conditional statement used to make decisions"
    },
    
    {
        "question": "What is the purpose of an if-else statement?",
        "A": "To repeat a block of code",
        "B": "To choose between two blocks of code",
        "C": "To define a function",
        "D": "To import a module",
        "answer": "To choose between two blocks of code"
    },
    
    {
        "question": "What is an elif ladder?",
        "A": "A loop inside another loop",
        "B": "A series of multiple conditions checked one after another",
        "C": "A function with many arguments",
        "D": "A type of variable",
        "answer": "A series of multiple conditions checked one after another"
    },
    
    {
        "question": "What is a nested if statement?",
        "A": "An if statement inside another if statement",
        "B": "A loop inside an if statement",
        "C": "An if statement without a condition",
        "D": "An if statement inside a function only",
        "answer": "An if statement inside another if statement"
    },
    
    {
        "question": "What is the purpose of the ternary operator in Python?",
        "A": "To define a function",
        "B": "To write a simple if-else statement in one line",
        "C": "To create a loop",
        "D": "To compare two lists",
        "answer": "To write a simple if-else statement in one line"
    },
    
    {
        "question": "Which of the following values is considered False in Python?",
        "A": "1",
        "B": "\"Python\"",
        "C": "[]",
        "D": "\"0\"",
        "answer": "[]"
    },
    
    {
        "question": "What is truthiness in Python?",
        "A": "The ability of an object to be evaluated as True or False",
        "B": "The process of comparing two values",
        "C": "The process of creating variables",
        "D": "The process of type casting",
        "answer": "The ability of an object to be evaluated as True or False"
    },
    
    {
        "question": "What is match-case in Python?",
        "A": "A function",
        "B": "A pattern matching statement",
        "C": "A loop",
        "D": "A data type",
        "answer": "A pattern matching statement"
    },
    
    {
        "question": "Which Python version introduced match-case?",
        "A": "Python 2.7",
        "B": "Python 3.6",
        "C": "Python 3.10",
        "D": "Python 3.8",
        "answer": "Python 3.10"
    },
    
    {
        "question": "What is the purpose of the wildcard (_) in match-case?",
        "A": "To match any remaining case",
        "B": "To terminate the program",
        "C": "To skip a loop",
        "D": "To define a variable",
        "answer": "To match any remaining case"
    },
    
    {
        "question": "Can a single case in match-case match multiple values?",
        "A": "Yes",
        "B": "No",
        "C": "Only integers",
        "D": "Only strings",
        "answer": "Yes"
    },
    
    {
        "question": "When should match-case be preferred?",
        "A": "When checking many possible values of the same variable",
        "B": "When creating lists",
        "C": "When defining classes",
        "D": "When importing modules",
        "answer": "When checking many possible values of the same variable"
    },
    
    {
        "question": "Can match-case perform pattern matching?",
        "A": "Yes",
        "B": "No",
        "C": "Only with numbers",
        "D": "Only with strings",
        "answer": "Yes"
    },
    
    {
        "question": "What happens if no case matches and no wildcard case is provided?",
        "A": "Python raises an error",
        "B": "Nothing is executed",
        "C": "The program stops immediately",
        "D": "The first case is executed",
        "answer": "Nothing is executed"
    },
    
    {
        "question": "Can match-case replace long if-elif ladders?",
        "A": "Yes, in many situations",
        "B": "No",
        "C": "Only for loops",
        "D": "Only for functions",
        "answer": "Yes, in many situations"
    },
    
    {
        "question": "Which keyword starts a match-case statement?",
        "A": "case",
        "B": "switch",
        "C": "match",
        "D": "select",
        "answer": "match"
    },
    
    {
        "question": "Which keyword is used to define each branch inside a match statement?",
        "A": "if",
        "B": "elif",
        "C": "case",
        "D": "default",
        "answer": "case"
    },
    
    {
        "question": "Can match-case compare strings?",
        "A": "Yes",
        "B": "No",
        "C": "Only numbers",
        "D": "Only Boolean values",
        "answer": "Yes"
    },
    
    {
        "question": "Can match-case compare integers?",
        "A": "Yes",
        "B": "No",
        "C": "Only strings",
        "D": "Only lists",
        "answer": "Yes"
    },
    
    {
        "question": "Which statement is generally better for checking a large number of fixed values?",
        "A": "match-case",
        "B": "while",
        "C": "for",
        "D": "try-except",
        "answer": "match-case"
    },
    
    {
        "question": "What is a for loop used for?",
        "A": "To iterate over a sequence",
        "B": "To define a function",
        "C": "To import a module",
        "D": "To create a class",
        "answer": "To iterate over a sequence"
    },
    
    {
        "question": "What is a while loop used for?",
        "A": "To repeat a block of code while a condition is True",
        "B": "To create a variable",
        "C": "To define a function",
        "D": "To import a module",
        "answer": "To repeat a block of code while a condition is True"
    },
    
    {
        "question": "What is the main difference between a for loop and a while loop?",
        "A": "A for loop is used for iteration, while a while loop runs until a condition becomes False",
        "B": "A while loop is always faster",
        "C": "A for loop can only work with numbers",
        "D": "There is no difference",
        "answer": "A for loop is used for iteration, while a while loop runs until a condition becomes False"
    },
    
    {
        "question": "What does the range() function return?",
        "A": "A list",
        "B": "A tuple",
        "C": "A range object",
        "D": "A set",
        "answer": "A range object"
    },
    
    {
        "question": "What is the default starting value of range(5)?",
        "A": "1",
        "B": "5",
        "C": "0",
        "D": "-1",
        "answer": "0"
    },
    
    {
        "question": "What is the default step value of range()?",
        "A": "0",
        "B": "1",
        "C": "2",
        "D": "-1",
        "answer": "1"
    },
    
    {
        "question": "How many arguments can range() accept?",
        "A": "Only one",
        "B": "Only two",
        "C": "One, two, or three",
        "D": "Only three",
        "answer": "One, two, or three"
    },
    
    {
        "question": "What does range(start, stop, step) specify?",
        "A": "Start value, end value, and increment/decrement",
        "B": "Minimum, maximum, average",
        "C": "Row, column, index",
        "D": "Length, width, height",
        "answer": "Start value, end value, and increment/decrement"
    },
    
    {
        "question": "Is the stop value included in range()?",
        "A": "Yes",
        "B": "No",
        "C": "Only for even numbers",
        "D": "Only for odd numbers",
        "answer": "No"
    },
    
    {
        "question": "Can range() use a negative step value?",
        "A": "Yes",
        "B": "No",
        "C": "Only with positive numbers",
        "D": "Only in Python 2",
        "answer": "Yes"
    },
    
    {
        "question": "What is an infinite loop?",
        "A": "A loop that never ends unless interrupted",
        "B": "A loop that runs only once",
        "C": "A loop with syntax errors",
        "D": "A loop without variables",
        "answer": "A loop that never ends unless interrupted"
    },
    
    {
        "question": "Which statement can stop an infinite loop?",
        "A": "continue",
        "B": "pass",
        "C": "break",
        "D": "return",
        "answer": "break"
    },
    
    {
        "question": "What is a nested loop?",
        "A": "A loop inside another loop",
        "B": "A loop with an if statement",
        "C": "A loop without a condition",
        "D": "A loop inside a function only",
        "answer": "A loop inside another loop"
    },
    
    {
        "question": "What does the break statement do?",
        "A": "Skips the current iteration",
        "B": "Terminates the loop immediately",
        "C": "Repeats the loop",
        "D": "Does nothing",
        "answer": "Terminates the loop immediately"
    },
    
    {
        "question": "What does the continue statement do?",
        "A": "Stops the loop completely",
        "B": "Skips the current iteration and continues with the next iteration",
        "C": "Restarts the program",
        "D": "Exits the function",
        "answer": "Skips the current iteration and continues with the next iteration"
    },
    
    {
        "question": "What does the pass statement do?",
        "A": "Terminates the loop",
        "B": "Skips the current iteration",
        "C": "Acts as a placeholder and performs no action",
        "D": "Repeats the loop",
        "answer": "Acts as a placeholder and performs no action"
    },
    
    {
        "question": "What is the difference between break and continue?",
        "A": "break exits the loop, while continue skips the current iteration",
        "B": "Both perform the same task",
        "C": "continue exits the loop, while break skips the iteration",
        "D": "Neither affects the loop",
        "answer": "break exits the loop, while continue skips the current iteration"
    },
    
    {
        "question": "When is the else block of a loop executed?",
        "A": "When the loop finishes normally without a break",
        "B": "After every iteration",
        "C": "Only when break is executed",
        "D": "Only for while loops",
        "answer": "When the loop finishes normally without a break"
    },
    
    {
        "question": "Does the else block execute if the loop is terminated using break?",
        "A": "Yes",
        "B": "No",
        "C": "Only for for loops",
        "D": "Only for while loops",
        "answer": "No"
    },
    
    {
        "question": "How can you iterate through each character of a string?",
        "A": "Using a for loop",
        "B": "Using del",
        "C": "Using pass",
        "D": "Using import",
        "answer": "Using a for loop"
    },
    
    {
        "question": "What is a list in Python?",
        "A": "An immutable collection of items",
        "B": "A mutable ordered collection of items",
        "C": "A collection of unique items only",
        "D": "A collection of key-value pairs",
        "answer": "A mutable ordered collection of items"
    },
    
    {
        "question": "Why are lists mutable?",
        "A": "Because their elements can be modified after creation",
        "B": "Because they cannot store numbers",
        "C": "Because they are faster than tuples",
        "D": "Because they cannot be indexed",
        "answer": "Because their elements can be modified after creation"
    },
    
    {
        "question": "How do you create an empty list?",
        "A": "()",
        "B": "{}",
        "C": "[]",
        "D": "<>",
        "answer": "[]"
    },
    
    {
        "question": "What is indexing in a list?",
        "A": "Accessing elements using their position",
        "B": "Sorting the list",
        "C": "Removing elements",
        "D": "Copying the list",
        "answer": "Accessing elements using their position"
    },
    
    {
        "question": "What does negative indexing mean?",
        "A": "Indexing starts from the middle",
        "B": "Indexing starts from the end of the list",
        "C": "Negative values cannot be stored",
        "D": "The list is reversed automatically",
        "answer": "Indexing starts from the end of the list"
    },
    
    {
        "question": "What is slicing in Python?",
        "A": "Deleting elements from a list",
        "B": "Accessing a portion of a sequence",
        "C": "Sorting a list",
        "D": "Creating a tuple",
        "answer": "Accessing a portion of a sequence"
    },
    
    {
        "question": "What does append() do?",
        "A": "Adds an element at the beginning",
        "B": "Adds an element at the end of the list",
        "C": "Removes the last element",
        "D": "Sorts the list",
        "answer": "Adds an element at the end of the list"
    },
    
    {
        "question": "What is the difference between append() and extend()?",
        "A": "Both do the same thing",
        "B": "append() adds a single item, extend() adds multiple items from an iterable",
        "C": "append() removes items, extend() adds items",
        "D": "extend() works only with tuples",
        "answer": "append() adds a single item, extend() adds multiple items from an iterable"
    },
    
    {
        "question": "What is the difference between append() and insert()?",
        "A": "append() adds at the end, insert() adds at a specified index",
        "B": "Both always add at the beginning",
        "C": "insert() removes elements",
        "D": "append() sorts the list",
        "answer": "append() adds at the end, insert() adds at a specified index"
    },
    
    {
        "question": "What is the difference between remove() and pop()?",
        "A": "Both remove elements by index",
        "B": "remove() deletes by value, pop() removes by index and returns the removed element",
        "C": "remove() returns the removed element",
        "D": "There is no difference",
        "answer": "remove() deletes by value, pop() removes by index and returns the removed element"
    },
    
    {
        "question": "What does clear() do?",
        "A": "Deletes the list variable",
        "B": "Removes all elements from the list",
        "C": "Sorts the list",
        "D": "Copies the list",
        "answer": "Removes all elements from the list"
    },
    
    {
        "question": "What does copy() do?",
        "A": "Creates a shallow copy of the list",
        "B": "Deletes the list",
        "C": "Sorts the list",
        "D": "Reverses the list",
        "answer": "Creates a shallow copy of the list"
    },
    
    {
        "question": "What is the difference between sort() and sorted()?",
        "A": "Both return a new sorted list",
        "B": "sort() modifies the original list, sorted() returns a new sorted sequence",
        "C": "sorted() modifies the original list",
        "D": "sort() works only with numbers",
        "answer": "sort() modifies the original list, sorted() returns a new sorted sequence"
    },
    
    {
        "question": "What is the difference between reverse() and reversed()?",
        "A": "reverse() modifies the original list, reversed() returns a reverse iterator",
        "B": "Both create a new reversed list",
        "C": "reverse() works only on tuples",
        "D": "There is no difference",
        "answer": "reverse() modifies the original list, reversed() returns a reverse iterator"
    },
    
    {
        "question": "Which function returns the number of elements in a list?",
        "A": "count()",
        "B": "size()",
        "C": "len()",
        "D": "length()",
        "answer": "len()"
    },
    
    {
        "question": "Which function returns the largest element in a list?",
        "A": "large()",
        "B": "max()",
        "C": "highest()",
        "D": "top()",
        "answer": "max()"
    },
    
    {
        "question": "Which function returns the smallest element in a list?",
        "A": "small()",
        "B": "min()",
        "C": "lowest()",
        "D": "bottom()",
        "answer": "min()"
    },
    
    {
        "question": "Which method counts the occurrences of a value in a list?",
        "A": "find()",
        "B": "count()",
        "C": "search()",
        "D": "index()",
        "answer": "count()"
    },
    
    {
        "question": "Which operator is commonly used to merge two lists?",
        "A": "+",
        "B": "-",
        "C": "*",
        "D": "%",
        "answer": "+"
    },
    
    {
        "question": "What is a nested list?",
        "A": "A list containing another list as an element",
        "B": "A list containing only numbers",
        "C": "A sorted list",
        "D": "An empty list",
        "answer": "A list containing another list as an element"
    },
    
    {
        "question": "How can duplicate elements be removed from a list?",
        "A": "Using set()",
        "B": "Using tuple()",
        "C": "Using dict()",
        "D": "Using len()",
        "answer": "Using set()"
    },
    
    {
        "question": "How can you traverse a nested list?",
        "A": "Using nested loops",
        "B": "Using break",
        "C": "Using pass",
        "D": "Using continue",
        "answer": "Using nested loops"
    },
    
    {
        "question": "What is a shallow copy?",
        "A": "A copy where nested mutable objects are shared",
        "B": "A completely independent copy of all objects",
        "C": "A copy that cannot be modified",
        "D": "A copy stored in a file",
        "answer": "A copy where nested mutable objects are shared"
    },
    
    {
        "question": "What is a deep copy?",
        "A": "A copy that shares all nested objects",
        "B": "A completely independent copy, including nested objects",
        "C": "A copy of only immutable objects",
        "D": "A copy stored in memory",
        "answer": "A completely independent copy, including nested objects"
    },
    
    {
        "question": "What is the difference between a shallow copy and a deep copy?",
        "A": "Both behave the same",
        "B": "A shallow copy shares nested objects, while a deep copy creates independent copies",
        "C": "A deep copy uses less memory",
        "D": "A shallow copy is always slower",
        "answer": "A shallow copy shares nested objects, while a deep copy creates independent copies"
    },
    
    {
        "question": "What happens when you write a = b for a list?",
        "A": "A new copy of the list is created",
        "B": "Both variables refer to the same list object",
        "C": "The list becomes immutable",
        "D": "Python raises an error",
        "answer": "Both variables refer to the same list object"
    },
    
    {
        "question": "What happens when you write a = b.copy()?",
        "A": "Both variables refer to the same object",
        "B": "A shallow copy of the list is created",
        "C": "A deep copy is created",
        "D": "The list is deleted",
        "answer": "A shallow copy of the list is created"
    },
    
    {
        "question": "Which module provides the deepcopy() function?",
        "A": "math",
        "B": "copy",
        "C": "random",
        "D": "os",
        "answer": "copy"
    },
    
    {
        "question": "What is a tuple in Python?",
        "A": "A mutable ordered collection",
        "B": "An immutable ordered collection",
        "C": "An unordered collection",
        "D": "A key-value collection",
        "answer": "An immutable ordered collection"
    },
    
    {
        "question": "Why are tuples immutable?",
        "A": "Because their elements cannot be changed after creation",
        "B": "Because they can store only numbers",
        "C": "Because they are unordered",
        "D": "Because they cannot be indexed",
        "answer": "Because their elements cannot be changed after creation"
    },
    
    {
        "question": "How do you create an empty tuple?",
        "A": "[]",
        "B": "{}",
        "C": "()",
        "D": "<>",
        "answer": "()"
    },
    
    {
        "question": "How do you create a tuple with multiple elements?",
        "A": "[1, 2, 3]",
        "B": "(1, 2, 3)",
        "C": "{1, 2, 3}",
        "D": "<1, 2, 3>",
        "answer": "(1, 2, 3)"
    },
    
    {
        "question": "How do you create a single-element tuple?",
        "A": "(5)",
        "B": "[5]",
        "C": "(5,)",
        "D": "{5}",
        "answer": "(5,)"
    },
    
    {
        "question": "What is the difference between (5) and (5,)?",
        "A": "Both are tuples",
        "B": "(5) is an integer, while (5,) is a tuple",
        "C": "(5) is a list",
        "D": "There is no difference",
        "answer": "(5) is an integer, while (5,) is a tuple"
    },
    
    {
        "question": "What is tuple packing?",
        "A": "Combining multiple values into a single tuple",
        "B": "Sorting a tuple",
        "C": "Deleting tuple elements",
        "D": "Converting a tuple into a list",
        "answer": "Combining multiple values into a single tuple"
    },
    
    {
        "question": "What is tuple unpacking?",
        "A": "Assigning tuple elements to multiple variables",
        "B": "Deleting a tuple",
        "C": "Creating nested tuples",
        "D": "Sorting a tuple",
        "answer": "Assigning tuple elements to multiple variables"
    },
    
    {
        "question": "What is extended unpacking in Python?",
        "A": "Using * to collect multiple elements during unpacking",
        "B": "Creating multiple tuples",
        "C": "Packing nested tuples",
        "D": "Sorting tuples",
        "answer": "Using * to collect multiple elements during unpacking"
    },
    
    {
        "question": "What is a nested tuple?",
        "A": "A tuple containing another tuple as an element",
        "B": "A tuple containing only integers",
        "C": "An empty tuple",
        "D": "A sorted tuple",
        "answer": "A tuple containing another tuple as an element"
    },
    
    {
        "question": "Can a tuple contain mutable objects like lists?",
        "A": "No",
        "B": "Yes",
        "C": "Only strings",
        "D": "Only integers",
        "answer": "Yes"
    },
    
    {
        "question": "Can the mutable objects inside a tuple be modified?",
        "A": "No",
        "B": "Yes",
        "C": "Only in Python 2",
        "D": "Only if the tuple has one element",
        "answer": "Yes"
    },
    
    {
        "question": "What is the main advantage of a tuple over a list?",
        "A": "Tuples are immutable and generally faster",
        "B": "Tuples can only store integers",
        "C": "Tuples allow duplicate keys",
        "D": "Tuples are mutable",
        "answer": "Tuples are immutable and generally faster"
    },
    
    {
        "question": "Which consumes less memory?",
        "A": "List",
        "B": "Tuple",
        "C": "Both consume the same memory",
        "D": "Dictionary",
        "answer": "Tuple"
    },
    
    {
        "question": "Which is generally faster for iteration?",
        "A": "List",
        "B": "Tuple",
        "C": "Set",
        "D": "Dictionary",
        "answer": "Tuple"
    },
    
    {
        "question": "When should a tuple be preferred over a list?",
        "A": "When the data should not change",
        "B": "When frequent modifications are required",
        "C": "When duplicate values are not allowed",
        "D": "When key-value pairs are needed",
        "answer": "When the data should not change"
    },
    
    {
        "question": "Can a tuple be used as a dictionary key?",
        "A": "Yes, if it contains only immutable elements",
        "B": "No",
        "C": "Only in Python 2",
        "D": "Only if it contains integers",
        "answer": "Yes, if it contains only immutable elements"
    },
    
    {
        "question": "What is the output of print(True + True)?",
        "A": "TrueTrue",
        "B": "2",
        "C": "1",
        "D": "Error",
        "answer": "2"
    },
    
    {
        "question": "What is the output of print(False + True)?",
        "A": "0",
        "B": "1",
        "C": "FalseTrue",
        "D": "Error",
        "answer": "1"
    },
    
    {
        "question": "What is the output of print(bool(''))?",
        "A": "True",
        "B": "False",
        "C": "None",
        "D": "Error",
        "answer": "False"
    },
    
    {
        "question": "What is the output of print(bool('0'))?",
        "A": "False",
        "B": "True",
        "C": "0",
        "D": "Error",
        "answer": "True"
    },
    
    {
        "question": "What is the output of print(10 and 0 or 5)?",
        "A": "10",
        "B": "0",
        "C": "5",
        "D": "True",
        "answer": "5"
    },
    
    {
        "question": "What is the output of print(5 > 3 > 2)?",
        "A": "False",
        "B": "True",
        "C": "Error",
        "D": "5",
        "answer": "True"
    },
    
    {
        "question": "What is the output of print(10 / 3)?",
        "A": "3",
        "B": "3.0",
        "C": "3.3333333333333335",
        "D": "4",
        "answer": "3.3333333333333335"
    },
    
    {
        "question": "What is the output of print(10 // 3)?",
        "A": "3",
        "B": "3.0",
        "C": "4",
        "D": "1",
        "answer": "3"
    },
    
    {
        "question": "What is the output of print(10 % 3)?",
        "A": "3",
        "B": "1",
        "C": "0",
        "D": "10",
        "answer": "1"
    },
    
    {
        "question": "What is the output of print(2 ** 3 ** 2)?",
        "A": "64",
        "B": "512",
        "C": "256",
        "D": "81",
        "answer": "512"
    },
    
    {
        "question": "What happens when a syntax error occurs in Python?",
        "A": "The program continues execution",
        "B": "The program stops before execution",
        "C": "Python ignores the error",
        "D": "Only a warning is displayed",
        "answer": "The program stops before execution"
    },
    
    {
        "question": "What happens if an exception is not handled?",
        "A": "The program terminates and displays a traceback",
        "B": "Python automatically fixes the error",
        "C": "The exception is ignored",
        "D": "The program restarts",
        "answer": "The program terminates and displays a traceback"
    },
    
    {
        "question": "What is garbage collection in Python?",
        "A": "A process that removes unused objects from memory",
        "B": "A method for sorting data",
        "C": "A module for file handling",
        "D": "A way to compress programs",
        "answer": "A process that removes unused objects from memory"
    },
    
    {
        "question": "What is the purpose of Python's memory management?",
        "A": "To automatically allocate and release memory for objects",
        "B": "To create variables",
        "C": "To compile Python code",
        "D": "To install packages",
        "answer": "To automatically allocate and release memory for objects"
    },
    
    {
        "question": "Why is Python popular in Artificial Intelligence and Machine Learning?",
        "A": "Because of its simple syntax and rich library support",
        "B": "Because it is the fastest programming language",
        "C": "Because it only supports AI",
        "D": "Because it does not require libraries",
        "answer": "Because of its simple syntax and rich library support"
    },
    
    {
        "question": "What is eval() in Python?",
        "A": "A function that evaluates and executes a Python expression from a string",
        "B": "A function that creates a list",
        "C": "A function that imports modules",
        "D": "A function that opens files",
        "answer": "A function that evaluates and executes a Python expression from a string"
    },
    
    {
        "question": "What type of value does eval() return?",
        "A": "Always a string",
        "B": "The result of the evaluated expression",
        "C": "Always an integer",
        "D": "None",
        "answer": "The result of the evaluated expression"
    },
    
    {
        "question": "Which function returns the data type of an object?",
        "A": "id()",
        "B": "type()",
        "C": "len()",
        "D": "input()",
        "answer": "type()"
    },
    
    {
        "question": "Which function checks whether an object belongs to a specific type?",
        "A": "type()",
        "B": "id()",
        "C": "isinstance()",
        "D": "bool()",
        "answer": "isinstance()"
    },
    
    {
        "question": "What does len() return?",
        "A": "The memory address",
        "B": "The number of items in an object",
        "C": "The data type",
        "D": "The largest value",
        "answer": "The number of items in an object"
    },
    
    {
        "question": "Which function returns the largest element from an iterable?",
        "A": "max()",
        "B": "min()",
        "C": "len()",
        "D": "sum()",
        "answer": "max()"
    },
    
    {
        "question": "Which function returns the smallest element from an iterable?",
        "A": "max()",
        "B": "sum()",
        "C": "min()",
        "D": "len()",
        "answer": "min()"
    },
    
    {
        "question": "Which function returns the sum of all elements in an iterable?",
        "A": "count()",
        "B": "sum()",
        "C": "len()",
        "D": "max()",
        "answer": "sum()"
    },
    
    {
        "question": "Which function returns the absolute value of a number?",
        "A": "round()",
        "B": "abs()",
        "C": "pow()",
        "D": "int()",
        "answer": "abs()"
    },
    
    {
        "question": "Which function rounds a number to the nearest integer by default?",
        "A": "round()",
        "B": "abs()",
        "C": "pow()",
        "D": "float()",
        "answer": "round()"
    },
    
    {
        "question": "Which function returns both the index and value while iterating?",
        "A": "range()",
        "B": "enumerate()",
        "C": "zip()",
        "D": "map()",
        "answer": "enumerate()"
    },
    
    {
        "question": "What does zip() do?",
        "A": "Sorts a list",
        "B": "Combines elements from multiple iterables",
        "C": "Removes duplicate values",
        "D": "Creates a dictionary",
        "answer": "Combines elements from multiple iterables"
    },
    
    {
        "question": "Which function returns an iterator after applying a function to every item?",
        "A": "filter()",
        "B": "map()",
        "C": "zip()",
        "D": "sorted()",
        "answer": "map()"
    },
    
    {
        "question": "Which function returns only the elements that satisfy a condition?",
        "A": "map()",
        "B": "filter()",
        "C": "zip()",
        "D": "range()",
        "answer": "filter()"
    },
    
    {
        "question": "Which module contains the reduce() function?",
        "A": "math",
        "B": "functools",
        "C": "random",
        "D": "os",
        "answer": "functools"
    },
    
    {
        "question": "What does sorted() return?",
        "A": "A new sorted list",
        "B": "None",
        "C": "The original list",
        "D": "A tuple",
        "answer": "A new sorted list"
    },
    
    {
        "question": "Which function is commonly used to display help for Python objects?",
        "A": "guide()",
        "B": "help()",
        "C": "info()",
        "D": "manual()",
        "answer": "help()"
    },
    
    {
        "question": "Which keyword is used to define a function in Python?",
        "A": "function",
        "B": "func",
        "C": "define",
        "D": "def",
        "answer": "def"
    },
    
    {
        "question": "What is the default return value of a function if no return statement is used?",
        "A": "0",
        "B": "False",
        "C": "None",
        "D": "Empty string",
        "answer": "None"
    },
    
    {
        "question": "Can a Python function return multiple values?",
        "A": "Yes",
        "B": "No",
        "C": "Only integers",
        "D": "Only strings",
        "answer": "Yes"
    },
    
    {
        "question": "What is the difference between a function definition and a function call?",
        "A": "A definition creates a function, while a call executes it",
        "B": "Both are the same",
        "C": "A call creates a function",
        "D": "A definition deletes a function",
        "answer": "A definition creates a function, while a call executes it"
    },
    
    {
        "question": "What are parameters in Python?",
        "A": "Values passed during a function call",
        "B": "Variables defined in the function definition",
        "C": "Return values of a function",
        "D": "Global variables",
        "answer": "Variables defined in the function definition"
    },
    
    {
        "question": "What are arguments in Python?",
        "A": "Variables defined in a function",
        "B": "Values passed to a function during a call",
        "C": "Global variables",
        "D": "Return values",
        "answer": "Values passed to a function during a call"
    },
    
    {
        "question": "What happens if a function does not have a return statement?",
        "A": "It returns 0",
        "B": "It returns False",
        "C": "It returns None",
        "D": "It raises an error",
        "answer": "It returns None"
    },
    
    {
        "question": "What is the difference between print() and return?",
        "A": "print() displays output, while return sends a value back to the caller",
        "B": "Both perform the same task",
        "C": "return displays output",
        "D": "print() ends the function",
        "answer": "print() displays output, while return sends a value back to the caller"
    },
    
    {
        "question": "Can a function return multiple values?",
        "A": "Yes",
        "B": "No",
        "C": "Only integers",
        "D": "Only strings",
        "answer": "Yes"
    },
    
    {
        "question": "Are functions first-class objects in Python?",
        "A": "Yes",
        "B": "No",
        "C": "Only built-in functions",
        "D": "Only user-defined functions",
        "answer": "Yes"
    },
    
    {
        "question": "What does it mean that functions are first-class objects?",
        "A": "Functions can be assigned to variables, passed as arguments, and returned from other functions",
        "B": "Functions can only be called once",
        "C": "Functions cannot be stored in variables",
        "D": "Functions always return integers",
        "answer": "Functions can be assigned to variables, passed as arguments, and returned from other functions"
    },
    
    {
        "question": "Can a function be assigned to a variable?",
        "A": "Yes",
        "B": "No",
        "C": "Only built-in functions",
        "D": "Only lambda functions",
        "answer": "Yes"
    },
    
    {
        "question": "Can a function be passed as an argument to another function?",
        "A": "Yes",
        "B": "No",
        "C": "Only recursive functions",
        "D": "Only lambda functions",
        "answer": "Yes"
    },
    
    {
        "question": "Where are local variables accessible?",
        "A": "Only inside the function in which they are defined",
        "B": "Anywhere in the program",
        "C": "Only inside classes",
        "D": "Only inside loops",
        "answer": "Only inside the function in which they are defined"
    },
    
    {
        "question": "Where are global variables accessible?",
        "A": "Only inside one function",
        "B": "Throughout the program unless shadowed",
        "C": "Only inside loops",
        "D": "Only inside classes",
        "answer": "Throughout the program unless shadowed"
    },
    
    {
        "question": "What is variable shadowing?",
        "A": "A local variable having the same name as a global variable",
        "B": "Deleting a variable",
        "C": "Copying a variable",
        "D": "Renaming a function",
        "answer": "A local variable having the same name as a global variable"
    },
    
    {
        "question": "What does LEGB stand for?",
        "A": "Local, Enclosing, Global, Built-in",
        "B": "Local, External, Global, Basic",
        "C": "Loop, Enclosing, Global, Built-in",
        "D": "Local, End, Global, Block",
        "answer": "Local, Enclosing, Global, Built-in"
    },
    
    {
        "question": "Which scope is searched first according to the LEGB rule?",
        "A": "Global",
        "B": "Built-in",
        "C": "Local",
        "D": "Enclosing",
        "answer": "Local"
    },
    
    {
        "question": "What are positional arguments?",
        "A": "Arguments passed according to their position",
        "B": "Arguments passed by name",
        "C": "Optional arguments",
        "D": "Global arguments",
        "answer": "Arguments passed according to their position"
    },
    
    {
        "question": "What are keyword arguments?",
        "A": "Arguments passed using parameter names",
        "B": "Arguments passed by position only",
        "C": "Arguments passed automatically",
        "D": "Arguments that cannot have default values",
        "answer": "Arguments passed using parameter names"
    },
    
    {
        "question": "What are default arguments?",
        "A": "Parameters with predefined values",
        "B": "Arguments passed by position",
        "C": "Arguments passed by keyword",
        "D": "Required arguments",
        "answer": "Parameters with predefined values"
    },
    
    {
        "question": "What happens if a required argument is missing during a function call?",
        "A": "Python uses None automatically",
        "B": "Python raises a TypeError",
        "C": "The function returns False",
        "D": "The program ignores the missing argument",
        "answer": "Python raises a TypeError"
    },
    
    {
        "question": "Can a function have both positional and keyword arguments?",
        "A": "Yes",
        "B": "No",
        "C": "Only in Python 2",
        "D": "Only lambda functions",
        "answer": "Yes"
    },
    
    {
        "question": "What are variable-length arguments in Python?",
        "A": "Arguments that allow a function to accept any number of values",
        "B": "Arguments with fixed length",
        "C": "Arguments used only in loops",
        "D": "Arguments that cannot be modified",
        "answer": "Arguments that allow a function to accept any number of values"
    },
    
    {
        "question": "What does *args collect?",
        "A": "Keyword arguments",
        "B": "Positional arguments as a tuple",
        "C": "Arguments as a list",
        "D": "Only integer values",
        "answer": "Positional arguments as a tuple"
    },
    
    {
        "question": "What does **kwargs collect?",
        "A": "Positional arguments",
        "B": "Keyword arguments as a dictionary",
        "C": "Arguments as a tuple",
        "D": "Only string values",
        "answer": "Keyword arguments as a dictionary"
    },
    
    {
        "question": "When should you use *args?",
        "A": "When the number of positional arguments is unknown",
        "B": "When only one argument is allowed",
        "C": "When creating classes",
        "D": "When importing modules",
        "answer": "When the number of positional arguments is unknown"
    },
    
    {
        "question": "When should you use **kwargs?",
        "A": "When the number of keyword arguments is unknown",
        "B": "When using only positional arguments",
        "C": "When writing loops",
        "D": "When creating tuples",
        "answer": "When the number of keyword arguments is unknown"
    },
    
    {
        "question": "Can positional arguments appear after keyword arguments in a function call?",
        "A": "Yes",
        "B": "No",
        "C": "Only in Python 2",
        "D": "Only for built-in functions",
        "answer": "No"
    },
    
    {
        "question": "What is a nested function?",
        "A": "A function defined inside another function",
        "B": "A recursive function",
        "C": "A built-in function",
        "D": "A lambda function",
        "answer": "A function defined inside another function"
    },
    
    {
        "question": "Why are nested functions used?",
        "A": "To organize code and hide helper functions",
        "B": "To increase program size",
        "C": "To replace loops",
        "D": "To create global variables",
        "answer": "To organize code and hide helper functions"
    },
    
    {
        "question": "Can an inner function access variables of its outer function?",
        "A": "Yes",
        "B": "No",
        "C": "Only global variables",
        "D": "Only local variables",
        "answer": "Yes"
    },
    
    {
        "question": "What is lexical scoping?",
        "A": "Variables are resolved based on where functions are defined",
        "B": "Variables are always global",
        "C": "Variables are resolved randomly",
        "D": "Variables exist only inside loops",
        "answer": "Variables are resolved based on where functions are defined"
    },
    
    {
        "question": "Can a nested function be returned from its outer function?",
        "A": "Yes",
        "B": "No",
        "C": "Only in Python 2",
        "D": "Only if it has no parameters",
        "answer": "Yes"
    },
    
    {
        "question": "What is a closure?",
        "A": "A nested function that remembers variables from its enclosing scope",
        "B": "A recursive function",
        "C": "A built-in function",
        "D": "A loop",
        "answer": "A nested function that remembers variables from its enclosing scope"
    },
    
    {
        "question": "Which keyword allows modification of a variable in the enclosing scope?",
        "A": "global",
        "B": "nonlocal",
        "C": "local",
        "D": "static",
        "answer": "nonlocal"
    },
    
    {
        "question": "What is the difference between global and nonlocal?",
        "A": "global accesses module-level variables, nonlocal accesses enclosing function variables",
        "B": "Both perform the same task",
        "C": "nonlocal creates global variables",
        "D": "global works only inside classes",
        "answer": "global accesses module-level variables, nonlocal accesses enclosing function variables"
    },
    
    {
        "question": "What is a higher-order function?",
        "A": "A function that accepts or returns another function",
        "B": "A function with many parameters",
        "C": "A recursive function",
        "D": "A built-in function",
        "answer": "A function that accepts or returns another function"
    },
    
    {
        "question": "Which of the following is a higher-order function?",
        "A": "map()",
        "B": "len()",
        "C": "type()",
        "D": "input()",
        "answer": "map()"
    },
    
    {
        "question": "What does map() return?",
        "A": "A map object (iterator)",
        "B": "A list",
        "C": "A tuple",
        "D": "A dictionary",
        "answer": "A map object (iterator)"
    },
    
    {
        "question": "What does filter() return?",
        "A": "A filter object (iterator)",
        "B": "A list",
        "C": "A tuple",
        "D": "A set",
        "answer": "A filter object (iterator)"
    },
    
    {
        "question": "Which function from functools reduces an iterable to a single value?",
        "A": "map()",
        "B": "filter()",
        "C": "reduce()",
        "D": "sorted()",
        "answer": "reduce()"
    },
    
    {
        "question": "Which function is commonly used with a custom key for sorting objects?",
        "A": "sorted()",
        "B": "range()",
        "C": "zip()",
        "D": "input()",
        "answer": "sorted()"
    },
    
]